### ISSUE TITLE
Clicking in Windows Terminal v1.9.1942.0 causes a panic due to an unhandled event flag

### ISSUE THREAD

**Issue by ClementTsang** [crossterm-rs/crossterm#588]
**Describe the bug**

Original bug report is from https://github.com/ClementTsang/bottom/issues/562, for context.

The problem appears to be that on at least Windows Terminal v1.9.1942.0, mouse clicks can cause a panic due to an event flag that isn't handled by crossterm.

The error actually seems to be coming from [crossterm_winapi](https://github.com/crossterm-rs/crossterm-winapi), but it seemed better to report it here.

The backtrace I got when I initially encountered the problem is as follows:
```bash
thread '<unnamed>' panicked at 'Event flag 3 does not exist.', C:\Users\Clement\.cargo\registry\src\github.com-1ecc6299db9ec823\crossterm_winapi-0.8.0\src\structs\input.rs:227:18
   0: backtrace::backtrace::trace_unsynchronized<closure-0>
             at C:\Users\Clement\.cargo\registry\src\github.com-1ecc6299db9ec823\backtrace-0.3.59\src\backtrace\mod.rs:66
   1: backtrace::backtrace::trace<closure-0>
             at C:\Users\Clement\.cargo\registry\src\github.com-1ecc6299db9ec823\backtrace-0.3.59\src\backtrace\mod.rs:53
   2: backtrace::capture::Backtrace::create
             at C:\Users\Clement\.cargo\registry\src\github.com-1ecc6299db9ec823\backtrace-0.3.59\src\capture.rs:176
   3: backtrace::capture::Backtrace::new
             at C:\Users\Clement\.cargo\registry\src\github.com-1ecc6299db9ec823\backtrace-0.3.59\src\capture.rs:140
   4: bottom::panic_hook
             at src\lib.rs:294
   5: btm::main::{{closure}}
             at src\bin\main.rs:121
```

I can't replicate this behaviour with powershell.exe, so I assume it's something specific to the Windows Terminal.

**To Reproduce**

1. Install [Windows Terminal v1.9.1942.0](https://github.com/microsoft/terminal/releases/tag/v1.9.1942.0)
2. Clone the crossterm repo
3. Try running the event-poll-read example and click around a lot to trigger a bunch of events.
4. If you hit the same problem I did, it should crash after clicking around a lot, and you might get an output like so:

```
Blocking poll() & non-blocking read()
 - Keyboard, mouse and terminal resize events enabled
 - Prints "." every second if there's no event
 - Hit "c" to print current cursor position
 - Use Esc to quit

.
Event::Mouse(MouseEvent { kind: Down(Left), column: 39, row: 39, modifiers: NONE })
Event::Mouse(MouseEvent { kind: Up(Left), column: 39, row: 39, modifiers: NONE })
Event::Mouse(MouseEvent { kind: Moved, column: 39, row: 39, modifiers: NONE })
Event::Mouse(MouseEvent { kind: Moved, column: 40, row: 39, modifiers: NONE })
Event::Mouse(MouseEvent { kind: Moved, column: 41, row: 39, modifiers: NONE })
Event::Mouse(MouseEvent { kind: Down(Left), column: 41, row: 39, modifiers: NONE })
thread 'main' panicked at 'Event flag 3 does not exist.', C:\Users\Clement\.cargo\registry\src\github.com-1ecc6299db9ec823\crossterm_winapi-0.8.0\src\structs\input.rs:227:18
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
error: process didn't exit successfully: `C:\Users\Clement\Documents\GitHub\crossterm\target\debug\examples\event-poll-read.exe` (exit code: 101)
PS C:\Users\Clement\Documents\GitHub\crossterm\examples>
```

**Expected behavior**

Either the keycode is handled or it shouldn't cause a panic. 

**OS**

Windows 10 Education, 21H2, 19043.1110

**Terminal/Console**

Windows Terminal v1.9.1942.0

**Comment by ClementTsang** [comment]
Running the example with `RUST_BACKTRACE=1`:

```powershell
PS C:\Users\Clement\Documents\GitHub\crossterm\examples> cargo r --example event-poll-read
    Finished dev [unoptimized + debuginfo] target(s) in 0.16s
     Running `C:\Users\Clement\Documents\GitHub\crossterm\target\debug\examples\event-poll-read.exe`
Blocking poll() & non-blocking read()
 - Keyboard, mouse and terminal resize events enabled
 - Prints "." every second if there's no event
 - Hit "c" to print current cursor position
 - Use Esc to quit

Event::Mouse(MouseEvent { kind: Drag(Left), column: 61, row: 26, modifiers: NONE })
Event::Mouse(MouseEvent { kind: Drag(Left), column: 61, row: 25, modifiers: NONE })
Event::Mouse(MouseEvent { kind: Drag(Left), column: 61, row: 24, modifiers: NONE })
Event::Mouse(MouseEvent { kind: Drag(Left), column: 61, row: 23, modifiers: NONE })
Event::Mouse(MouseEvent { kind: Drag(Left), column: 60, row: 23, modifiers: NONE })
Event::Mouse(MouseEvent { kind: Drag(Left), column: 59, row: 22, modifiers: NONE })
Event::Mouse(MouseEvent { kind: Drag(Left), column: 58, row: 22, modifiers: NONE })
Event::Mouse(MouseEvent { kind: Drag(Left), column: 57, row: 21, modifiers: NONE })
Event::Mouse(MouseEvent { kind: Drag(Left), column: 55, row: 21, modifiers: NONE })
Event::Mouse(MouseEvent { kind: Drag(Left), column: 54, row: 20, modifiers: NONE })
Event::Mouse(MouseEvent { kind: Drag(Left), column: 52, row: 20, modifiers: NONE })
Event::Mouse(MouseEvent { kind: Drag(Left), column: 51, row: 20, modifiers: NONE })
Event::Mouse(MouseEvent { kind: Drag(Left), column: 51, row: 19, modifiers: NONE })
Event::Mouse(MouseEvent { kind: Drag(Left), column: 50, row: 19, modifiers: NONE })
Event::Mouse(MouseEvent { kind: Drag(Left), column: 50, row: 18, modifiers: NONE })
Event::Mouse(MouseEvent { kind: Drag(Left), column: 50, row: 17, modifiers: NONE })
Event::Mouse(MouseEvent { kind: Down(Left), column: 50, row: 17, modifiers: NONE })
thread 'main' panicked at 'Event flag 3 does not exist.', C:\Users\Clement\.cargo\registry\src\github.com-1ecc6299db9ec823\crossterm_winapi-0.8.0\src\structs\input.rs:227:18
stack backtrace:
   0: std::panicking::begin_panic_handler
             at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b\/library\std\src\panicking.rs:493
   1: std::panicking::begin_panic_fmt
             at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b\/library\std\src\panicking.rs:435
   2: crossterm_winapi::structs::input::{{impl}}::from
             at C:\Users\Clement\.cargo\registry\src\github.com-1ecc6299db9ec823\crossterm_winapi-0.8.0\src\structs\input.rs:227
   3: core::convert::{{impl}}::into<u32,crossterm_winapi::structs::input::EventFlags>
             at C:\Users\Clement\.rustup\toolchains\stable-x86_64-pc-windows-msvc\lib\rustlib\src\rust\library\core\src\convert\mod.rs:538
   4: crossterm_winapi::structs::input::{{impl}}::from
             at C:\Users\Clement\.cargo\registry\src\github.com-1ecc6299db9ec823\crossterm_winapi-0.8.0\src\structs\input.rs:84
   5: core::convert::{{impl}}::into<winapi::um::wincontypes::MOUSE_EVENT_RECORD,crossterm_winapi::structs::input::MouseEvent>
             at C:\Users\Clement\.rustup\toolchains\stable-x86_64-pc-windows-msvc\lib\rustlib\src\rust\library\core\src\convert\mod.rs:538
   6: crossterm_winapi::structs::input::{{impl}}::from
             at C:\Users\Clement\.cargo\registry\src\github.com-1ecc6299db9ec823\crossterm_winapi-0.8.0\src\structs\input.rs:308
   7: core::convert::{{impl}}::into<winapi::um::wincontypes::INPUT_RECORD,crossterm_winapi::structs::input::InputRecord>
             at C:\Users\Clement\.rustup\toolchains\stable-x86_64-pc-windows-msvc\lib\rustlib\src\rust\library\core\src\convert\mod.rs:538
   8: crossterm_winapi::console::Console::read_single_input_event
             at C:\Users\Clement\.cargo\registry\src\github.com-1ecc6299db9ec823\crossterm_winapi-0.8.0\src\console.rs:172
   9: crossterm::event::source::windows::{{impl}}::try_read
             at C:\Users\Clement\Documents\GitHub\crossterm\src\event\source\windows.rs:43
  10: crossterm::event::read::InternalEventReader::poll<crossterm::event::filter::EventFilter>
             at C:\Users\Clement\Documents\GitHub\crossterm\src\event\read.rs:64
  11: crossterm::event::poll_internal<crossterm::event::filter::EventFilter>
             at C:\Users\Clement\Documents\GitHub\crossterm\src\event.rs:223
  12: crossterm::event::poll
             at C:\Users\Clement\Documents\GitHub\crossterm\src\event.rs:158
  13: event_poll_read::print_events
             at .\event-poll-read.rs:25
  14: event_poll_read::main
             at .\event-poll-read.rs:55
  15: core::ops::function::FnOnce::call_once<fn() -> core::result::Result<tuple<>, std::io::error::Error>,tuple<>>
             at C:\Users\Clement\.rustup\toolchains\stable-x86_64-pc-windows-msvc\lib\rustlib\src\rust\library\core\src\ops\function.rs:227
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
error: process didn't exit successfully: `C:\Users\Clement\Documents\GitHub\crossterm\target\debug\examples\event-poll-read.exe` (exit code: 101)
```

**Comment by TimonPost** [comment]
Interestingly there is no event flag 3.In the [parsing code](https://github.com/crossterm-rs/crossterm-winapi/blob/master/src/structs/input.rs#L219) there is no check for an event 3. 

And the microsoft form is not mention this event flag:

![image](https://user-images.githubusercontent.com/19969910/127025468-2a26460c-4130-43ff-8b6a-723f9aa62500.png)

**Comment by TimonPost** [comment]
Actually, there is a todo to replace this with `TryResult` allowing for a non panic error return. However, we should just handle all event types and it should theoretically not be possible for the panic to hit. 

![image](https://user-images.githubusercontent.com/19969910/127025487-66ae574e-a80f-40fe-a3ed-d4002392c5ad.png)

**Comment by vojta7** [comment]
Even though Microsoft documentation doesn't mention it, the value of [dwEventFlags](https://docs.microsoft.com/en-us/windows/console/mouse-event-record-str) clearly looks like bitflags that can be ORed together.

I tried to look into commits of Microsoft terminal and I think that [this commit](https://github.com/microsoft/terminal/commit/0d61466afedf255cfe4ba117efec54320936961c) might introduce this behavior.

[This method](https://github.com/microsoft/terminal/blob/d43a14c63fc0192d84bde4f6b510d232777c454e/src/terminal/parser/InputStateMachineEngine.cpp#L847) also looks interesting, it creates eventFlags in a way that multiple values can be present.

**Comment by TimonPost** [comment]
Ah they use bitmap and add multiple values to the event flag. That could result in that result being given. However, I wonder if that is intended behavior.

**Comment by ClementTsang** [comment]
Just for purposes of keeping track of stuff, https://github.com/crossterm-rs/crossterm-winapi/pull/20 seems to be a PR that would at least somewhat alleviate the problems in this issue.

**Comment by Berrysoft** [comment]
This bug is also caught in VSCode. Flag 3 appears when I try to drag some parts.

**Comment by Canop** [comment]
I encounter this bug too ( https://github.com/Canop/safecloset/issues/17 ).

Is there some progress here ? Can we put a fix in place or at least mitigate the problem (panicking is clearly not right) ?

**Comment by ClementTsang** [comment]
For anyone who's still affected, upgrade your version of crossterm to 0.22.1 or later, it uses a newer version of crossterm-winapi which will instead just return an unknown result rather than a hard panic.

**Comment by ClementTsang** [comment]
Feel free to close this if you want, btw - the issue I reported is technically fixed, though I know you wanted to handle the additional bitflag case in the future.
